# Generated by Django 2.2.1 on 2019-05-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190520_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='todo',
            name='Apellido',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='Edad',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='todo',
            name='Nombre',
            field=models.CharField(default='', max_length=20),
        ),
    ]
